ipc = on
preload = /home/sh1ragami/.config/hypr/wallpaper.png
wallpaper = desc:AU Optronics 0x662D,/home/sh1ragami/.config/hypr/wallpaper.png
wallpaper = eDP-1,/home/sh1ragami/.config/hypr/wallpaper.png
wallpaper = ,/home/sh1ragami/.config/hypr/wallpaper.png
splash = false
