general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. 少し放置したら画面を暗くする (節電 & 予告)
listener {
    timeout = 150                                # 2.5分
    on-timeout = brightnessctl set 10%           # 輝度を下げる
    on-resume = brightnessctl set 100%           # 戻ったら輝度を復元
}

# 2. 5分放置でロック
listener {
    timeout = 300                                
    on-timeout = loginctl lock-session
}

# 3. ロック後、さらに放置したらディスプレイの信号を切る
listener {
    timeout = 330                                # ロックの30秒後
    on-timeout = hyprctl dispatch dpms off       # 画面消灯
    on-resume = hyprctl dispatch dpms on        # 復帰で点灯
}
