-- Generated by nwg-displays on 2026-07-07 at 17:18:28. Do not edit manually.

hl.monitor({
    output = "desc:AU Optronics 0x662D",
    mode = "1920x1080@60.05",
    position = "3911x1644",
    scale = 1.33
})
hl.monitor({
    output = "desc:Dell Inc. DELL S2421HGF C47Y973",
    mode = "1920x1080@60.0",
    position = "5355x1376",
    scale = 1.0
})
