general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    col.active_border = rgba(a9b665ff)
    col.inactive_border = rgba(282a3aff)
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    dim_inactive = false
    blur {
        enabled = false
    }
    shadow {
        enabled = false
    }
}
