# ==========================================================
# --- フォント設定 (隙間調整済み) ---
# ==========================================================
font_family      JetBrainsMono NF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0
# 文字の間隔を詰める (100%未満で狭くなります)

# 合字の有効化
disable_ligatures never

# --- デザイン・透過設定 ---
include opacity.conf
background_blur    1
dynamic_background_opacity yes


# ウィンドウの余白 (文字が端に寄りすぎるのを防ぐ)
window_padding_width 4

# --- タブバーのデザイン ---
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
active_tab_foreground   #111
active_tab_background   #eee
inactive_tab_foreground #666
inactive_tab_background #333

# ==========================================================
# --- カラースキーム (Theme Selector Integration) ---
# ==========================================================
include theme.conf

# ==========================================================
# --- 高度な設定 ---
# ==========================================================
allow_remote_control yes
listen_on unix:@mykitty
# URLをクリック可能にする
detect_urls yes
url_color #73daca
url_style curly

# ベルの音をオフ
enable_audio_bell no

# 設定の再読み込みショートカットを有効化 (Ctrl+Shift+F5)
map ctrl+shift+f5 load_config_file

open_url_with firefox --new-window
