# Study Theme Kitty Config (Soft Dark #282a3a)
background            #282a3a
foreground            #d5ddf6
background_opacity    1.0

selection_background  #393d54
selection_foreground  #d5ddf6

# Black
color0 #494e6e
color8 #5e648c
# Red
color1 #ff757f
color9 #ff757f
# Green
color2 #c3e88d
color10 #c3e88d
# Yellow
color3 #ffc777
color11 #ffc777
# Blue
color4 #82aaff
color12 #82aaff
# Magenta
color5 #c099ff
color13 #c099ff
# Cyan
color6 #86e2d5
color14 #86e2d5
# White
color7  #9199c2
color15 #d5ddf6
